#!/bin/bash

# Install package(s)
#
# usage: ynh_package_install name [name [...]]
# | arg: name - the package name to install
ynh_package_try_install() {
    ynh_apt -o Dpkg::Options::=--force-confdef \
            -o Dpkg::Options::=--force-confold install $@
}
