#!/bin/bash

# NOTE This helper is DEPRECATED

# Need also the helper https://github.com/YunoHost-Apps/Experimental_helpers/blob/master/ynh_handle_getopts_args/ynh_handle_getopts_args

# Reload (or other actions) a service and print a log in case of failure.
#
# usage: ynh_system_reload service_name [action]
# | arg: -n, --service_name= - Name of the service to reload
# | arg: -a, --action= - Action to perform with systemctl. Default: reload
ynh_system_reload () {
        # Declare an array to define the options of this helper.
        declare -Ar args_array=( [n]=service_name= [a]=action= )
        local service_name
        local action
        # Manage arguments with getopts
        ynh_handle_getopts_args "$@"
        local action=${action:-reload}

        # Reload, restart or start and print the log if the service fail to start or reload
        systemctl $action $service_name || ( journalctl --lines=20 -u $service_name >&2 && false)
}
