#!/bin/bash

# Reload (or restart) a service and print a log in case of failure.
#
# usage: ynh_system_reload service_name
# | arg: service_name - Name of the service to reload
ynh_system_reload () {
        local service_name=$1

        # Reload the service (or restart if reload isn't available)
        # The service will be started if it isn't
        # And print the log if the service fail to start or reload
        systemctl reload-or-restart $service_name || ( journalctl --lines=20 -u $service_name >&2 && false)
}
