#!/bin/bash
 
ynh_add_repos(){
  name_repos="$1"
  url_repos="$2"
  echo "# $name_repos
    ${url_repos}" 
    > "/etc/apt/sources.list.d/$name_repos.list"
}

ynh_add_pin_repo() {
  name_repos="$1"
  pin="$2"
  origin="$3"
  echo "Package: *
       Pin: release o=$origin,a=$name_repos
       Pin-Priority: $pin" \
    > "/etc/apt/preferences.d/$name_repos"
}

ynh_add_secure_backport() {
   name_repos="debian-backports"
   origin="Debian"
   lsb_version="$(ynh_get_debian_release)"
   url="deb https://ftp.debian.org/debian $lsb_version-backports main"
   pin="450"
   ynh_add_repos $name_repos $url 
   ynh_add_pin_repo $name_repos $origin $pin
}

ynh_rm_secure_repos() {
  name_repos=$1
  ynh_secure_remove "/etc/apt/preferences.d/$name_repos"
  ynh_secure_remove "/etc/apt/sources.list.d/$name_repos.list"
}
