#!/bin/bash
 
ynh_add_repos(){
  NAME_REPOS=$1
  URL_REPOS=$2
  touch "/etc/apt/source.list.d/$NAME_REPOS.list"
  echo "# $NAME_REPOS
    ${URL_REPOS}" \
    > '/etc/apt/sources.list.d/$NAME_REPOS.list'
}

ynh_add_pin_repo() {
  NAME_REPOS=$1
  PIN=$2
  ORIGIN=$3
  if [ -f /etc/apt/preferences.d/$NAME_REPOS ]
  then 
    ynh_secure_remove /etc/apt/preferences.d/$NAME_REPOS
  fi
  touch /etc/apt/preferences.d/$NAME_REPOS
  echo "Package: *
       Pin: release o=$ORIGIN,a=$NAME_REPOS
       Pin-Priority: $PIN" \
    > '/etc/apt/preferences.d/$NAME_REPOS'
}

ynh_add_secure_backport() {
   NAME_REPOS=debian-backports
   ORIGIN=Debian
   LSB_VERSION=$(ynh_get_debian_release)
   URL="deb https://ftp.debian.org/debian $LSB_VERSION-backports main"
   PIN=450
   ynh_add_repos $NAME_REPOS $URL 
   ynh_add_pin_repo $NAME_REPOS $ORIGIN $PIN
}
